version: '3.1'

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: "johndoe"
      POSTGRES_PASSWORD: "randompassword"
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - items

  deepapi:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      PORT: 4444
      DATABASE_URL: postgres://johndoe:randompassword@postgres:5432/mydb?schema=public
    ports:
      - 4444:4444
    expose:
      - 4444
    depends_on:
      - postgres
    networks:
      - items

  deepfrontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NUXT_PUBLIC_BASE_URL: http://127.0.0.1:4444
    ports:
      - 3333:3000
    expose:
      - 3333
    depends_on:
      - deepapi
    networks:
      - items

volumes:
  db:
    driver: local

networks:
  items:
    driver: bridge

