version: '3.1'

services:
  postgres:
    image: postgres:14
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
