name: Deploy backend application
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    name: Deploy backend on google cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

    # Setup gcloud CLI
    - uses: GoogleCloudPlataform/github-actions/setup-gloud@master