name: Deploy backend application
env:
  VERCEL_ORG_ID: ${{ vercel.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ vercel.VERCEL_PROJECT_ID }}
  DATABASE_URL: ${{ vercel.VERCEL_DATABASE_URL }}
on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    name: Deploy backend on vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ vercel.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ vercel.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ vercel.VERCEL_TOKEN }}